# -*- coding: utf-8 -*-
"""HW 5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1zcXPCbGPzyNUjNHzMUSikDl7tMk4Loq3

##Python Supply Chain Buyer Order System

This code creates the catalog using a dictionary. the items are the keys and the prices are the values. This helps making it easier to look up a price of an item when the buyer adds it to the purchase request.
"""

catalog={
    "printer paper": 6.50,
    "packing tape": 3.25,
    "shipping labels": 9.75,
    "nitrile gloves": 12.50,
    "box cutter": 4.95,
    "safety goggles": 8.25,
    "pallet wrap": 14.00
}

"""This code creates the function that builds the purchase request. it uses a while loop so the buyer can keep entering items until they are ready to submit it. If the item is in the catalog it will be added to the request list. If the items isn't in the catalog then the code will print an error message and will ask the user again."""

def build_request(catalog):
    request=[]
    while True:
        item = input("Enter an item to request type submit to finish: ").strip().lower()
        if item == "submit":
            break
        elif item in catalog:
            request.append(item)
            print(f"Added {item} to the purchase request")
        else:
            print("Item not in catalog, Please choose from the catalog.")
    return request

"""This code shows the function calculating the subtotal. the function loops through each item in the list and is able to find the price from the catalog dictionary then prints the item and price. Then it adds the price to the subtotal."""

def calculate_subtotal(request, catalog):
    subtotal = 0.0
    print("Purchase Request Summary:")
    for item in request:
        price = catalog[item]
        print(f"{item}: ${price:.2f}")
        subtotal += price
    print(f"Subtotal: ${subtotal:.2f}")
    return subtotal

"""This function adds overhead and shipping to the subtotal. The shipping fee is $15 and the overhead is 8% of the subtotal. The final total can be found by adding the subtotal, shippingm and the overhead together."""

def shipping_and_overhead(subtotal):
    shipping= 15.00
    overhead= 0.08 * subtotal
    final_total= subtotal + shipping + overhead
    print(f"Shipping: ${shipping:.2f}")
    print(f"Overhead (8%): ${overhead:.2f}")
    print(f"Final Total: ${final_total:.2f}")
    return final_total

"""The main function is responsible for running the whole program. It is able to call the function that is building the request then it calls the function that deals with the subtotal and it calls the shipping and overhead function as well. Functions are useful because it helps the code be organized instead of making one huge code block that will be hard to read and debug at times."""

def main():
    request= build_request(catalog)
    subtotal= calculate_subtotal(request, catalog)
    shipping_and_overhead(subtotal)
main()

main()