# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10mmvOQoZyOApkQaJv59pXzqtepADLvrD

#Ploty for interactive plots
"""

import pandas as pd
import plotly.express as px

df=pd.read_csv('Advertising_F.csv')

df.head()

px.scatter(df,x='TV',y="sales")

px.bar(df,x='City',y='sales',title='Total Sales')

fig=px.scatter_mapbox(df,lat='latitude', lon='longitude', size='sales', hover_name='City')
fig.update_layout(mapbox_style='carto-positron')

"""#Gradio"""

pip install gradio

import gradio as gr
import plotly.express as px

def create_plots(selected_city):
    if selected_city == 'All Cities':
        filtered_df = df
    else:
        filtered_df = df[df['City'] == selected_city]

    # Scatterplot of sales vs newspaper
    scatter_fig = px.scatter(filtered_df, x='newspaper', y='sales',
                             title=f'Sales vs. Newspaper for {selected_city}',
                             hover_name='City')

    # Map where TV is the size for each city
    map_fig = px.scatter_mapbox(filtered_df, lat='latitude', lon='longitude', size='TV',
                                hover_name='City', title=f'TV Ad Spend by Location for {selected_city}',
                                zoom=1 if selected_city == 'All Cities' else 5)
    map_fig.update_layout(mapbox_style='carto-positron')

    return scatter_fig, map_fig

cities = ['All Cities'] + df['City'].unique().tolist()

iface = gr.Interface(fn=create_plots,
                     inputs=gr.Dropdown(choices=cities, label='Select City', value='All Cities'),
                     outputs=[gr.Plot(label='Sales vs. Newspaper'), gr.Plot(label='TV Ad Spend Map')],
                     title='Advertising Data Explorer')

iface.launch(debug=True, share=True)

"""#Streamlit"""

# Commented out IPython magic to ensure Python compatibility.
# %%writefile my_app
# 
# import streamlit as streamlit
# import pandas as pd
# import plotly.express as px
# 
# df=pd.read_csv("Advertising_F.csv")
# 
# st.title("Advertising Effectiveness Micah")
# st.sidebar.header("Filters")
# x_var=st.sidebar.selectbox("X Axis", ["TV","radio","newspaper"])
# 
# fig=px.scatter(df,x=x_var,y="sales")
# st.ploty_chart(fig)
# 
# #dataframe
# st.write('###This is the data')
# st.dataframe(df)
# 
# #Show Map
# fig=px.scatter_mapbox(df,lat='latitude', lon='longitude', size='sales', hover_name='City')
# fig.update_layout(mapbox_style='carto-positron')
# st.plotly_chart(fig)
#